### ISSUE TITLE
ffmpeg 3 incompatibility

### ISSUE THREAD

**Issue by mruegenberg** [paperManu/splash#13]
When building on a system with FFMPEG 3, the following error occurs:

    ~/Downloads/splash/src/image_ffmpeg.cpp: In member function ‘void     Splash::Image_FFmpeg::readLoop()’:
    ~/Downloads/splash/src/image_ffmpeg.cpp:238:33: error: ‘avcodec_alloc_frame’ was not declared in this scope
         frame = avcodec_alloc_frame();

If an older version of ffmpeg is installed, it helps to force it to be found first e.g by doing `export PKG_CONFIG_PATH=/usr/lib/ffmpeg2.8/pkgconfig:$PKG_CONFIG_PATH` before the build.

**Comment by paperManu** [comment]
I made the corrections to the code, everything has been merged in branch develop.

There is an issue on my computer (Ubuntu 14.04) though: I find that the performances are far worse with ffmpeg 3.x than with ffmpeg 2.8. So either I did not compile ffmpeg 3.0.2 with the right flags, or I should also modify how I use it because it is notably worse.

**Comment by paperManu** [comment]
Just for notice, the performance issue with FFmpeg 3 has been solved.
