### ISSUE TITLE
not work when I click the "output selected mesh" button on the 3d view tool panel

### ISSUE THREAD

**Issue by Leroy-X** [paperManu/splash#19]
Hi, when I click the "output selected mesh" button on the 3d view tool panel, nothing happened, no error report, no file create, just nothing, but when I copy the python command and run it in the python console, it tell me :

Module pyshmdata was not found
{'FINISHED'}

I don't know how to solve it, what is pyshmdata, it make me very sad, you know, I have take lots time to install splash, very close to the success, but .....

The system is Elementary OS 64bit (like ubuntu).
Sorry for my bad english, very THANKS : )

**Comment by paperManu** [comment]
Hi Leroy-X,
This issue is due to the fact that Blender is looking for the pyshmdata module in the PYSHMDATA paths, and by default the module is installed in /usr/local/lib/python3.x which is not in PYSHMDATA by default.

So either you add it yourself (by specifying the PYSHMDATA environment variable in ~/.bashrc), or you can change the prefix while compiling shmdata by using the following command, which will set the install path to /usr/lib/python3.x:
```
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
```

**Comment by Leroy-X** [comment]
Thanks for your reply, our developer have solved it 🥇

**Comment by paperManu** [comment]
Ok great. I'll close this issue then.

I would be really happy to have some precisions about your project and everything, if you are willing to share. It would give me some perspective on how it is used =)
