### ISSUE TITLE
full screen window minimizes on lost focus

### ISSUE THREAD

**Issue by lindsey554** [paperManu/splash#28]
Hey,

I'm working with Splash on Ubuntu 16.04. I've compiled the master branch and installed, and am trying to copy your "Walkthrough" project. Everything seems to be working OK, except that the full screen window (which is correctly sent to the projector) minimizes when I click the GUI. 

I've tried setting the Windows hint "GLFW_AUTO_ICONIFY" to false and using a newer version of GLFW, but that doesn't seem to do anything. 

Any ideas? Is this a problem you're having?

Thanks

**Comment by paperManu** [comment]
Hey lindsey554,
That's odd, I've never had any such issue on Ubuntu or Mint (with any window manager). I don't use "real" fullscreen as it has the tendency to mess things up when multiple fullscreen windows are set, but rather a borderless window set to the display size.
Could you try setting the window dimensions and position to something else, so as to have a floating borderless window on the first display. Then check whether it minimizes whenever you click the GUI.

**Comment by paperManu** [comment]
I checked it quickly, and it indeed seems that the fullscreen option acts weirdly. To be fair, I have not used this option since the very beginning of Splash, as it is not the best way to get good performances.

What I do currently is create one window per GPU, and connect all cameras to this window. The cameras will be placed one next to another, for a maximum of 4 of them (I need to improve this). Then I set the window to be borderless, and placed correctly on a display.

So my fix will be the following: improve documentation about windows best practices, and remove the fullscreen option.
