### ISSUE TITLE
Issue starting up 

### ISSUE THREAD

**Issue by eamonndo1993** [paperManu/splash#30]
Hi there. Trying to install Splash on OSX Sierra. Everything seems to be working okay running all the code from the wiki in terminal, except for the splash --help command to actually attempt to run the program. I get the following error:

xxxxxxs-MacBook-Pro:~ xxxxxxxxxxxxx$ splash --help
dyld: Library not loaded: @loader_path/../Frameworks/Syphon.framework/Versions/A/Syphon
  Referenced from: /usr/local/bin/splash
  Reason: image not found
Abort trap: 6

Admittedly I'm not that good with Terminal code. Any advice would me massively appreciated.

Thanks

**Comment by paperManu** [comment]
The OSX build does not work well for me either currently, I need to find some time to dig into this. OSX port is not much used (as far as I know), and it is mainly used under Linux.

**Comment by romanrandom** [comment]
Anyone has figured this out? I'm not an OSX developer so I'm probably wasting my time trying to find a solution...

**Comment by rgov** [comment]
This is because the Syphon framework expects to be installed inside an .app bundle. It specifies an "install name" of `@loader_path/../Frameworks/Syphon.framework/Versions/A/Syphon` which tells the linker, "at runtime, this is where I'm going to be installed." The linker writes that path into the splash executable, so when the process runs, the dynamic loader knows where to find the Syphon library.

However, when splash was built as a command-line utility, it violated this expectation.

The solution is to use `install_name_tool` to either change the install name of the Syphon framework to be, say, hardcoded to a location in /Library/Frameworks, and then rebuild, or to patch the compiled splash executable to know where to find it.

**Comment by paperManu** [comment]
There was a tool to handle this used in Splash when macOS was supported : http://sourceforge.net/projects/macdylibbundler/

But anyway, the main issue nowadays is  that macOS does not support OpenGL 4.5 which is now required for Splash.
