### ISSUE TITLE
homebrew/versions has been depreciated

### ISSUE THREAD

**Issue by rnkn** [paperManu/splash#41]
The Homebrew versions tap [has been depreciated](https://docs.brew.sh/Versions.html), so the current installation instructions unfortunately won't work *exactly* as written.

The current Homebrew version of `glfw` is 3.2.1 — will that suffice to build splash?

**Comment by paperManu** [comment]
GLFW is now included as a submodule, and compiled along Splash. You should not have to install it yourself.

The OSX port is not maintained anymore, because I don't have the time nor the computer to test it, and OSX only supports OpenGL 4.1 (Splash needs OpenGL 4.5 now). If you have some time to try to make it work anyway, I'll happily verify and accept pull requests.
