### ISSUE TITLE
Camera window reliably stops rendering calibration markers and geometry

### ISSUE THREAD

**Issue by KevinCain** [paperManu/splash#70]
When calibrating with a flat plane, the camera window reliably stops rendering calibration markers and geometry.  This is persistent across reloading if the calibration for the camera is saved via CTRL-s.

- Below at top are (9) points, placed at the vertices shown with crosshairs correlated to the position in projector space, after pressing 'c' to calibrate.
- Below at center shows the rendering state after pressing 'c' a few more times to tune the alignment convergence, as suggested in @paperManu's documentation.  Note that the calibration spheres are now extruded lozenges!
- Below at bottom you'll see the result of pressing 'c' again -- the markers and geometry disappear, and are unresponsive to the wireframe/textured toggles.

![image](https://user-images.githubusercontent.com/5424003/51808002-e49a1580-2242-11e9-8029-d7ebf4aac37a.png)

In this state, I can't seem to delete the markers, as they aren't drawn.

Is this is known state, and how might I avoid this aside from refraining from multiple calibration runs?

**Comment by paperManu** [comment]
This is probably due to the near value of the Camera object which is set by default to high for the scale of your 3D model. You could try dividing it by 10, in the `Controls` panel.

Also, you should know that when calibrating a plane there is an infinity of intrinsic and extrinsic parameters which will match the projection. To improve the calibration, you could lock some of the parameters. For example if you know that your projector has no lens shift, you could set the `principalPoint` attribute of your `Camera` object to `(0.5, 0.5)` and lock it using the `L` button next to the attribute (still in the `Controls` panel). You can do the same for the field of view if you know its value.

![2019-01-27_18-59-53](https://user-images.githubusercontent.com/1152750/51808748-e9bc8c00-2265-11e9-8d3a-4dbae15b150c.png)

**Comment by KevinCain** [comment]
Good points, @paperManu!

I realize that a plane is a degenerate case for calibration, which is certainly not helping here.

As @paperManu intuited, I'm not using tilt-shift lenses; and locking the principal point (which is an ill-posed thing to compute, anyhow) helps a bit.  I can now do several calibration iterations before the model and control points disappear.

The model is in meter scale; the near plane is 0.1, and reducing to zero didn't seem to have an impact.

So this is a bit better for now, but not solved.  I'll leave this open until I have a chance to test with non-planar subjects.  Thanks again.

**Comment by paperManu** [comment]
The best would be for Splash to detect planar surfaces and act accordingly. For now the best approach is to lock the principal point and the fov, which should still leave room for the calibration process to happen.

**Comment by KevinCain** [comment]
A quick note to confirm that I'm seeing this on more than one machine, and also with non-planar target surfaces.  Most recently I'm seeing this reliably with a cylindrical screen.  This happens after many calibration iterations via 'c'.

In both cases, the low-poly initial model is sparse; but no sparser than the full dome example in the [Walkthrough](https://github.com/paperManu/splash/wiki/Walkthrough).

As @paperManu notes, planar surface detection is a good idea, since it's a common thing to have a flat projection surface.  Perhaps cylindrical screens are another 'auto-detection' candidate.
