### ISSUE TITLE
glm present but cannot be compiled

### ISSUE THREAD

**Issue by pietrondo** [paperManu/splash#9]
I'll try to compile on my arch linux, glm is installed (https://www.archlinux.org/packages/community/any/glm/)
```
configure: WARNING: glm/glm.hpp: present but cannot be compiled
configure: WARNING: glm/glm.hpp:     check for missing prerequisite headers?
configure: WARNING: glm/glm.hpp: see the Autoconf documentation
configure: WARNING: glm/glm.hpp:     section "Present But Cannot Be Compiled"
configure: WARNING: glm/glm.hpp: proceeding with the compiler's result
configure: WARNING:     ## --------------------------------------- ##
configure: WARNING:     ## Report this to emmanueldurand@gmail.com ##
configure: WARNING:     ## --------------------------------------- ##
checking for glm/glm.hpp... no
```

Someone could help me?

Thx

**Comment by paperManu** [comment]
Hi pietrondo,

You are the first (to my knowledge) to try to install Splash on Archlinux. My first thought would be to check that Clang is installed and that the `clang` and `clang++` commands are available. Check also that the `glm` directory is in your include path (basically, it should be in `/usr/include`).

Also, could you copy the `config.log` file in gist, so that I can check it?
